### ISSUE TITLE
Put extra attributes in Sentry context instead of extra

### ISSUE THREAD

**Issue by vansante** [samber/slog-sentry#5]
First of all thanks for your slog plugins! I have a question about the Sentry plugin: You are currently putting all non-recognized log attributes into the `Extra` field of the Sentry `Event` struct in the `DefaultConverter`. However, looking at the Sentry documentation, it seems like they should go into `Contexts` instead, as `Extra` [has been deprecated](https://docs.sentry.io/platforms/javascript/enriching-events/context/).

To quote:
```
Additional Data is deprecated in favor of structured contexts.

Sentry used to support adding unstructured "Additional Data" via setExtra.
```

Was it a conscious choice to put it in `Extra`? (Groupings are also supported in `Context` where in `Extra` they are not)

**Comment by samber** [comment]
I agree. If extra is deprecated, we must follow Sentry recommendations.

Context is not a drop-in replacement to Extra: https://docs.sentry.io/platforms/javascript/enriching-events/context/

K/V must be grouped under a key.

![image](https://github.com/samber/slog-sentry/assets/2951285/88cbf537-1c6c-4157-b0d4-b26bf43f184c)

![image](https://github.com/samber/slog-sentry/assets/2951285/519687b5-c659-4e79-8bbc-8959b702f16f)

**Comment by vansante** [comment]
Yeah I updated my issue after realising that. But thats an advantage, as that allows you to group unrecognised log groupings into there, and all the non grouped attributes can then go under an `Extra` Context for instance

**Comment by samber** [comment]
Can you review this PR please?

-> https://github.com/samber/slog-sentry/pull/6
