### ISSUE TITLE
Bug: "error" attribute always converts to map

### ISSUE THREAD

**Issue by inxhale777** [samber/slog-sentry#9]
Hello Mr. Samber. Thank you for your work, very appreciate you for this package

In current implementation I can't achieve stack trace in my sentry panel
And its seems what in default converter any errors converts to map, so stack is gone

At my screenshot, at 3rd step, "ok" is always false, because previously all error was converted to map

![image](https://github.com/samber/slog-sentry/assets/144735512/6acd0314-53b6-424e-82f6-f9423ce32cdf)

**Comment by inxhale777** [comment]
any by the way, on line 52, do you think it will be more practical to use `event.SetException` instead your own func `buildExceptions` ?

**Comment by samber** [comment]
Thanks for the suggestion. Can you review the following PR please? -> #10

**Comment by inxhale777** [comment]
yep, now works as expected, with no need of custom converter function
Thank you and have a good day!
![image](https://github.com/samber/slog-sentry/assets/144735512/bcbea3d0-9b50-4490-acbf-fa35f790f3bb)
